### ISSUE TITLE
Task lists aren't rendering properly

### ISSUE THREAD

**Issue by larryeby** [KostyaTretyak/marked-ts#8]
Documentation on how they should render are here: https://www.markdownguide.org/extended-syntax#task-lists

But the renderer is treating them like a list.

**Comment by KostyaTretyak** [comment]
As you can see, that there is "extended syntax" of markdown. For now, `markdown-ts` it's not supported. Try [override](https://github.com/KostyaTretyak/marked-ts#overriding-renderer-methods) `listitem` method.
